language: ruby
before_install:
  - sudo apt-get update
  - sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev
  - sudo apt-get install -qq graphicsmagick
  - gem install bundler -v 1.16.2
gemfile:
  - Gemfile
rvm:
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
script:
  - bundle exec rspec spec
