language: ruby
before_install:
  - sudo apt-get update
  - sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev
  - sudo apt-get install -qq graphicsmagick
  - gem install bundler -v 1.11.2
gemfile:
  - Gemfile
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
script:
  - bundle exec rspec spec
